# Уровень логирования
logLevel = "debug"

# Предзагрузка отладочных модулей
# preload = ["./debug-setup.ts"]

# Режим экономии памяти (полезно для отладки утечек)
# smol = true

[run]
# Не подавлять вывод команд
silent = false

[test]
# Предзагрузка только для тестов
coverage = true
